version: "3.8"
services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DEBUG=True

  ui:
    build:
      context: .
      target: ui
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app/ui
    environment:
      - BACKEND_URL=http://backend:8000/api/v1
    depends_on:
      - backend